import {
  Activity,
  ArrowUpRight,
  Bell,
  BriefcaseBusiness,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronRight,
  CircleUserRound,
  Cloud,
  Code2,
  Command,
  Copy,
  Download,
  ExternalLink,
  FolderGit2,
  GitFork,
  Github,
  GitCommitHorizontal,
  Grid2X2,
  Linkedin,
  Mail,
  MapPin,
  Menu,
  Monitor,
  Moon,
  Palette,
  Phone,
  Search,
  Server,
  Settings2,
  SlidersHorizontal,
  Star,
  Sun,
  TerminalSquare,
  Twitter,
  UsersRound,
  X,
} from 'lucide-react'

const icons = {
  activity: Activity,
  arrowUpRight: ArrowUpRight,
  bell: Bell,
  briefcase: BriefcaseBusiness,
  calendar: CalendarDays,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  cloud: Cloud,
  code: Code2,
  command: Command,
  copy: Copy,
  download: Download,
  'external-link': ExternalLink,
  folder: FolderGit2,
  fork: GitFork,
  gear: Settings2,
  github: Github,
  'git-commit': GitCommitHorizontal,
  grid: Grid2X2,
  linkedin: Linkedin,
  mail: Mail,
  mapPin: MapPin,
  menu: Menu,
  monitor: Monitor,
  moon: Moon,
  palette: Palette,
  phone: Phone,
  search: Search,
  server: Server,
  settings: SlidersHorizontal,
  star: Star,
  sun: Sun,
  terminal: TerminalSquare,
  twitter: Twitter,
  users: UsersRound,
  user: CircleUserRound,
  x: X,
}

export default function Icon({ name, size = 18, className = '', strokeWidth = 1.8 }) {
  const Component = icons[name]
  if (!Component) return null
  return <Component size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />
}
